# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-14 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('billing', '0003_auto_20180118_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='customer_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
