# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-09 14:19
from __future__ import unicode_literals

from django.db import migrations, models

import products.models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0004_auto_20171209_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path),
        ),
    ]
