# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-11 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0010_auto_20171211_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
