# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-05 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0011_auto_20171211_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=True),
        ),
    ]
